### PR TITLE
First pull for ARE_212 comments

### PR DESCRIPTION
**Pull request by lghackett**
Hello Professor Ligon,

I am at the halfway point for commenting the files (5/10 notebooks reviewed), so I think now is a good time to send you what I have so far. In general I added explanatory comments that hopefully will give students a little more insight into what certain lines are doing. 

If you look at the commit messages, there are two files (zeros, linear-non-linear) where I put small FIXME's. These are places where I either changed your code or had a question about it, so you may want to review that part and remove the FIXME if you consider that my change/question is OK. You can find these comments by opening the notebook and searching for "FIXME". 

If course if you have any feedback on the types of comments I am making please let me know.

Best, 

Lucy

### CODE REVIEW

**Comment by lghackett** [comment]
With this I have commented all the lecture notebooks! Let me know if you see anything that needs to be changed. 

Best, 

Lucy

**Review by ligon — APPROVED** [review]
Lucy, thanks for these thoughtful improvements.

**Comment by ligon** [comment]
Next time could you please be sure *not* to include extraneous files in the commit such as the files in .ipynb_checkpoints/?

**Comment by lghackett** [comment]
Hey Professor,

Of course; in the future I'll be more careful about extraneous files! My
apologies.

Lucy

**Pull request merged**
